name: CI Angular 

on: 
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.14.2.
        uses: actions/setup-node@v1
        with:
            node-version: 18.14.2

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
